import { Router } from 'express';
import { authRouter } from './modules/auth/auth.routes';
import { dashboardRouter } from './modules/dashboard/dashboard.routes';
import { productsRouter } from './modules/products/products.routes';
import { categoriesRouter, brandsRouter } from './modules/products/categories.routes';
import { customersRouter } from './modules/customers/customers.routes';
import { suppliersRouter } from './modules/suppliers/suppliers.routes';
import { usersRouter, rolesRouter } from './modules/users/users.routes';
import { invoicesRouter } from './modules/invoices/invoices.routes';
import { lposRouter } from './modules/lpos/lpos.routes';
import { quotationsRouter } from './modules/sales/quotations.routes';
import { salesOrdersRouter } from './modules/sales/salesorders.routes';
import { deliveryOrdersRouter } from './modules/sales/deliveryorders.routes';
import { creditNotesRouter } from './modules/sales/creditnotes.routes';
import { paymentsRouter } from './modules/payments/payments.routes';
import { warehousesRouter } from './modules/inventory/warehouses.routes';
import { grnsRouter } from './modules/purchases/grns.routes';
import { purchaseInvoicesRouter } from './modules/purchases/purchaseinvoices.routes';
import { debitNotesRouter } from './modules/purchases/debitnotes.routes';
import { inventoryRouter } from './modules/inventory/inventory.routes';
import { reportsRouter } from './modules/reports/reports.routes';
import { settingsRouter } from './modules/settings/settings.routes';
import { expensesRouter } from './modules/accounts/expenses.routes';

export const apiRouter = Router();

apiRouter.get('/health', (_req, res) => res.json({ ok: true, ts: new Date().toISOString() }));

apiRouter.use('/auth',            authRouter);
apiRouter.use('/dashboard',       dashboardRouter);
apiRouter.use('/products',        productsRouter);
apiRouter.use('/categories',      categoriesRouter);
apiRouter.use('/brands',          brandsRouter);
apiRouter.use('/customers',       customersRouter);
apiRouter.use('/suppliers',       suppliersRouter);
apiRouter.use('/users',           usersRouter);
apiRouter.use('/roles',           rolesRouter);
apiRouter.use('/quotations',      quotationsRouter);
apiRouter.use('/sales-orders',    salesOrdersRouter);
apiRouter.use('/invoices',        invoicesRouter);
apiRouter.use('/delivery-orders', deliveryOrdersRouter);
apiRouter.use('/credit-notes',    creditNotesRouter);
apiRouter.use('/payments',        paymentsRouter);
apiRouter.use('/warehouses',      warehousesRouter);
apiRouter.use('/lpos',            lposRouter);
apiRouter.use('/grns',            grnsRouter);
apiRouter.use('/purchase-invoices', purchaseInvoicesRouter);
apiRouter.use('/debit-notes',     debitNotesRouter);
apiRouter.use('/inventory',       inventoryRouter);
apiRouter.use('/reports',         reportsRouter);
apiRouter.use('/settings',        settingsRouter);
apiRouter.use('/expenses',        expensesRouter);
